name: salawat_quran
description: A modern offline-first Muslim companion with prayer times, Quran reading, Qibla and calendars.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  adhan_dart: ^2.0.1
  geolocator: ^14.0.2
  quran_data_dart: ^1.7.1
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^22.3.1
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  flutter_device_compass: ^2.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
